Task 6
Imirato/test-guru pull request #6
Opened 2022-08-13 19:43 UTC by Imirato

2022-08-14 18:12 UTC, BubuntuClu requested changes

2022-08-14 18:12 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = @test.questions.create(question_params)
Параметры с фронта могут быть не валидные, это надо учитывать
```
question = @test.questions.new(questions_params)
if question.save
  Render good
else
  Render bad
end
```

2022-08-14 18:12 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.order(:id)[params[:id].to_i - 1]
почему -1? какая логика тут?

а, ты полумаешь массив и в нем ищешь элемент? это неправильно, так как ID вопроса может быть не по порядку быть создан. почему бы просто не сделать `find`? так же как и с тестом

2022-08-14 18:12 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions
добавь опцию `shallow: true` для вопросов. посомтри как изменятся роуты и адаптируй код в контроллере под эти изменения

2022-08-15 09:47 UTC, Imirato commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.order(:id)[params[:id].to_i - 1]
Я хотела сделать так, чтобы в параметрах передавался ID вопроса относительно теста, а не глобальный.
Например, чтобы первый вопрос третьего теста вел url:
`/tests/3/questions/1`, 
а не 
`/tests/3/questions/32`

2022-08-15 17:17 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.order(:id)[params[:id].to_i - 1]
в этом случае надо тогда оринтироваться не на ID, а на какое-ниюудь доп поле типа `order`. но это не очевидное решение, по-умолчанию в роутах переадется ID и другие разработчики привыкли к такому. твое решение может сильно ошарашить. думаю в подобном случае надо делать не обычный круд-контроллер/роут, но что-то кастомное

2022-08-15 17:18 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :find_test, except: %i[show]
для удаления тест тоже не сможешь найти, так как параметра `test_id`в путях не будет

2022-08-15 17:18 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.order(:id)[params[:id].to_i - 1]
лучше пока с таким не эксперементировать, а освоить и понять стандартное поведение

2022-08-17 12:24 UTC, merged